### ISSUE TITLE
Possible to start in place other than center tile

### ISSUE THREAD

**Issue by malikh22** [smandla/Scrabble_GameStateFINAL#10]
1: placed a tile in a random spot (not center)
2: played a word
3: got points, game continued

This is not good because according to the game specifications, this should not be possible.

**Comment by smandla** [comment]
With the new updates made on this game, when a player decides to play a word, they must place a tile in the center of the game. The player then can only place a tile next to the other tile and no where else on the board.

**Comment by malikh22** [comment]
I tried this out and this is true. Nice work!
