### ISSUE TITLE
Trying to add a null tile to the board

### ISSUE THREAD

**Issue by morana21** [smandla/Scrabble_GameStateFINAL#2]
1. Tap tile you want to play
2. Tap anywhere on the board to play it
3. Tap the X where the tile was
4. Tap anywhere on the board 
...
Game crashes

**Comment by bunger20** [comment]
Game will only send place tile if the image button's image is something other than the red X. You can now touch them without causing the game to crash.

**Comment by morana21** [comment]
fixed: no longer crashes
