### ISSUE TITLE
Skip turn with tiles on board leaves tiles

### ISSUE THREAD

**Issue by robinsph21** [smandla/Scrabble_GameStateFINAL#4]
I played a tile onto the board, but didn't hit play, and instead hit skip, and I wasn't returned the tiles I played, but also wasn't scored them either. (I should either have gotten the tiles I placed back, or I should have been scored, or I should have been told that was an invalid move.)

**Comment by bunger20** [comment]
Tiles are now recalled (and placed back in hand) when skip is pressed.

**Comment by robinsph21** [comment]
Bug is fixed, tiles are returned. Very important to have fixed if I mess up.
