### ISSUE TITLE
Allowed Any 2 letters

### ISSUE THREAD

**Issue by AverageGatsby98** [smandla/Scrabble_GameStateFINAL#6]
(This is Spencer Rose leaving this)

Bug: if you put any one or two letters on the board, the game counts it as a valid word. Regardless of what the 2 letters are.

**Comment by bunger20** [comment]
Our for loops started a little too late; fixed starting point.

**Comment by AverageGatsby98** [comment]
You can no longer play only two tiles (unless they do actually spell out a word)
