### ISSUE TITLE
Won with illegal move

### ISSUE THREAD

**Issue by malikh22** [smandla/Scrabble_GameStateFINAL#9]
1: Played the word “Web”
2: Had two tiles left: “I” and “U”
3: Placed them both at the end of “Web” to create the non-word “Webiu”
4: Didn’t even press play, but won the game instantly 
5: It also still seems to continue the game after a win (it says it’s your turn but you can’t do anything)

This is not good because you shouldn’t be able to play a non-word, and you shouldn’t win before you actually play the word just because you don’t have tiles left.

**Comment by bunger20** [comment]
Just a bit of missing logic that has since been added.

**Comment by malikh22** [comment]
I was unable to play illegal moves this time. Nice work!
